import { Children, cloneElement, createContext, isValidElement, useContext, useEffect, useState } from 'react'

const translations = {
  en: {
    'O‘zbekcha': 'Uzbek', 'Tilni tanlang': 'Choose language', 'O\'yin-kulgi': 'Entertainment',
    'PULINGIZNI BOSHQARISH VAQTI': 'TAKE CONTROL OF YOUR MONEY', 'Rejalaringizga': 'Make a clear path', 'aniq yo‘l oching.': 'toward your goals.', 'Har bir xarajatni anglang. Har bir maqsadga yaqinlashing.': 'Understand every expense. Get closer to every goal.', 'oddiy budjet qoidasi': 'simple budgeting rule', 'Hisobingiz himoyalangan sessiya orqali saqlanadi': 'Your account is protected by a secure session',
    'SHAXSIY HISOB': 'PERSONAL ACCOUNT', 'Hisob yarating': 'Create an account', 'Hisobingizga kiring': 'Sign in to your account', 'Moliyaviy ma’lumotlaringiz shu hisobda saqlanadi.': 'Your financial data will be saved to this account.', 'Davom etish uchun email va parolingizni kiriting.': 'Enter your email and password to continue.', 'Kirish yoki ro‘yxatdan o‘tish': 'Sign in or create an account', 'Kirish': 'Sign in', 'Ro‘yxatdan o‘tish': 'Create account', 'Ismingiz': 'Your name', 'Ism va familiya': 'First and last name', 'Email manzil': 'Email address', 'Parol': 'Password', 'Parolni yashirish': 'Hide password', 'Parolni ko‘rsatish': 'Show password', 'Kamida 6 ta belgi': 'At least 6 characters', 'Parolingiz': 'Your password', 'Tekshirilmoqda…': 'Checking…', 'Hisob yaratish': 'Create account', 'Parolingiz serverda ochiq ko‘rinishda saqlanmaydi.': 'Your password is never stored in plain text.',
    'Menyuni yopish': 'Close menu', 'Menyuni ochish': 'Open menu', 'Hisobdan chiqish': 'Sign out', 'Menyu': 'MENU', 'Umumiy': 'Overview', 'Xarajatlar': 'Expenses', 'Maqsadlar': 'Goals', '30 kunlik challenge': '30-day challenge', 'Har bir kichik qadam katta maqsadga olib boradi.': 'Every small step leads to a bigger goal.', 'Maqsadlaringiz': 'Your goals', 'Shaxsiy moliya': 'Personal finance', 'Oldingi oy': 'Previous month', 'Keyingi oy': 'Next month', 'Boshqaruv paneli': 'Admin panel', 'Bildirishnomalar': 'Notifications', 'Yangi yozuv': 'New entry', 'MOLIYAVIY HOLATINGIZ': 'YOUR FINANCIAL SNAPSHOT', 'Salom, ': 'Hello, ', 'Bugun pulingiz qayerga ketayotganini ko‘rib chiqing.': 'See where your money is going today.', 'Shu oy': 'This month', 'Moliyaviy ko‘rsatkichlar': 'Financial overview', 'Umumiy balans': 'Total balance', 'OYLIK': 'MONTHLY', 'saqlanib qoldi': 'saved', 'Daromad va xarajat farqi': 'Income minus expenses', 'Daromad': 'Income', 'Jami daromad': 'Total income', 'Bu oy': 'This month', 'Xarajat': 'Expense', 'Jami xarajat': 'Total expenses', 'daromaddan': 'of income',
    'PUL OQIMI': 'CASH FLOW', 'Pulim qayerga ketmoqda?': 'Where is my money going?', 'Hafta': 'Week', 'Oy': 'Month', 'Xarajatlar tarkibi': 'Expense breakdown', 'Xarajat qo‘shsangiz, tarkibi shu yerda ko‘rinadi.': 'Add expenses to see a breakdown here.', 'Barcha kategoriyalar': 'All categories', 'KATEGORIYALAR': 'CATEGORIES', 'Eng ko‘p xarajat ': 'Highest spending: ', 'hozircha yo‘q': 'none yet', 'kategoriyasida.': 'category.', 'Batafsil': 'Details', 'Ko‘proq': 'More', 'JAMI': 'TOTAL', 'KATTA REJA': 'BIG PLANS', 'Jamg‘arma maqsadi': 'Savings goal', 'MAQSAD': 'GOAL', 'Maqsad nomi': 'Goal name', ' yig‘ildi': ' saved', 'Maqsadga qolgan': 'Remaining', 'Maqsadga yetish uchun': 'To reach your goal', 'Maqsadga yetdingiz!': 'Goal reached!', 'taxminan ': 'about ', ' oy': ' months', 'oylik jamg‘armani kiriting': 'set a monthly savings amount', 'Maqsad narxi': 'Goal amount', 'Har oy yig‘aman': 'Monthly savings', 'Jamg‘armaga pul qo‘shish': 'Add to savings', 'Masalan, 100 000': 'For example, 100,000', 'Qo‘shish': 'Add', '30 KUNLIK CHALLENGE': '30-DAY CHALLENGE', 'Bugun tejadingizmi?': 'Did you save today?', 'Har kuni ozgina tejang. 30 kundan so‘ng o‘zgarishni his qilasiz.': 'Save a little every day. Feel the difference after 30 days.', ' kun': ' days', 'Bugungi qadam bajarildi': 'Today’s step completed', 'Bugungi qadamni belgilash': 'Mark today’s step',
    'SO‘NGGI FAOLLIK': 'RECENT ACTIVITY', 'Oxirgi tranzaksiyalar': 'Recent transactions', 'Barchasini ko‘rish': 'View all', 'Bu oy uchun yozuvlar yo‘q. Birinchi tranzaksiyangizni qo‘shing.': 'No entries this month. Add your first transaction.', 'BUGUNGI MASLAHAT': 'TODAY’S TIP', 'Keyingi maslahat': 'Next tip', 'REJALASHTIRING': 'PLAN AHEAD', 'Kredit kalkulyatori': 'Loan calculator', 'Kredit summasi': 'Loan amount', 'Yillik foiz': 'Annual interest', 'Muddat': 'Term', 'Oylik to‘lov': 'Monthly payment', 'ODDIY REJA, BARQAROR NATIJA': 'A SIMPLE PLAN, STEADY RESULTS', 'Oylik pulni 3 qismga ajrating': 'Split your monthly income into 3 parts', '50 / 30 / 20 qoidasi byudjetni tushunarli va boshqariladigan qiladi.': 'The 50 / 30 / 20 rule makes budgeting clear and manageable.', 'ASOSIY EHTIYOJ': 'NEEDS', 'Avval zarur narsalar': 'Essentials first', 'Uy, oziq-ovqat, transport va kundalik to‘lovlar.': 'Housing, food, transport, and everyday bills.', 'SHAXSIY ISTAKLAR': 'WANTS', 'O‘zingizga ham joy qoldiring': 'Leave room for yourself', 'Hordiq, xaridlar va yoqtirgan mashg‘ulotlar.': 'Leisure, shopping, and activities you enjoy.', 'JAMG‘ARMA': 'SAVINGS', 'Kelajak uchun yig‘ing': 'Save for the future', 'Kutilmagan holatlar va katta maqsadlar uchun.': 'For unexpected expenses and bigger goals.', 'Yuqoriga': 'Back to top', 'Ma’lumotlaringiz faqat ushbu qurilmada saqlanadi': 'Your data is stored on this device only', 'YANGI YOZUV': 'NEW ENTRY', 'Tranzaksiya qo‘shish': 'Add a transaction', 'Nomi': 'Name', 'Masalan, tushlik': 'For example, lunch', 'Summa': 'Amount', 'Kategoriya': 'Category', 'Sana': 'Date', 'Tranzaksiyani saqlash': 'Save transaction', 'Yopish': 'Close', 'Oziq-ovqat': 'Food', 'Transport': 'Transport', 'O‘yin-kulgi': 'Entertainment', 'Xaridlar': 'Shopping', 'Uy va aloqa': 'Home & bills', 'Boshqa': 'Other', 'Ish haqi': 'Salary', 'Qo‘shimcha daromad': 'Extra income', 'so‘m': 'UZS', 'oy': 'months',
    'Moliya sahifasi': 'Finance dashboard', 'Chiqish': 'Sign out', 'BOSHQARUV': 'ADMINISTRATION', 'Foydalanuvchilar': 'Users', 'Hisob holatini boshqaring va kerak bo‘lsa sessiyani bekor qiling.': 'Manage account status and end sessions when needed.', 'Yangilash': 'Refresh', 'jami hisob': 'total accounts', 'Faol: ': 'Active: ', 'To‘xtatilgan: ': 'Suspended: ', 'RO‘YXAT': 'DIRECTORY', 'Hisoblar': 'Accounts', ' ta': '', 'Ro‘yxat yuklanmoqda…': 'Loading accounts…', 'Foydalanuvchi': 'User', 'Ro‘yxatdan o‘tgan': 'Registered', 'Holat': 'Status', 'Amal': 'Action', 'To‘xtatilgan': 'Suspended', 'Faol': 'Active', 'Ruxsat berish': 'Restore access', 'Chiqarish': 'Suspend', 'Hozircha ro‘yxatdan o‘tgan foydalanuvchi yo‘q.': 'No users have registered yet.', 'Hisobni to‘xtatish foydalanuvchini darhol chiqaradi; moliyaviy ma’lumotlari o‘chirilmaydi.': 'Suspending an account signs the user out immediately; financial data is not deleted.', 'Sessiya yakunlandi. Qayta kiring.': 'Your session ended. Please sign in again.', 'Hisobingiz sessiyasi bekor qilindi.': 'Your account session was revoked.', 'MoneyMaster yuklanmoqda': 'Loading MoneyMaster', 'Hisob ma’lumotlari yuklanmoqda': 'Loading account data', 'Juda ko‘p urinish. 1 daqiqadan keyin qayta urinib ko‘ring.': 'Too many attempts. Try again in one minute.', 'Hisobga qayta kiring.': 'Please sign in again.', 'Hisob faol emas yoki sessiya bekor qilingan.': 'This account is inactive or its session was revoked.', 'Administrator huquqi kerak.': 'Administrator access is required.', 'Ism va to‘g‘ri email kiriting.': 'Enter your name and a valid email address.', 'Parol kamida 6 ta belgidan iborat bo‘lsin.': 'Password must be at least 6 characters.', 'Bu email bilan hisob mavjud.': 'An account with this email already exists.', 'Email yoki parol noto‘g‘ri.': 'Incorrect email or password.', 'Foydalanuvchi topilmadi.': 'User not found.', 'Holatni yuboring.': 'Provide an account status.', 'So‘rov bajarilmadi.': 'The request could not be completed.', 'Server API JSON javob bermadi. Vercel deploy sozlamalarini tekshiring.': 'The server did not return API JSON. Check the Vercel deployment settings.', 'hisobini vaqtincha to‘xtatib, faol sessiyalarini bekor qilamizmi?': 'Do you want to suspend this account and revoke its active sessions?',
    '50 / 30 / 20 qoidasini sinab ko‘ring': 'Try the 50 / 30 / 20 rule', 'Daromadning 50 foizini ehtiyojlarga, 30 foizini istaklarga va 20 foizini jamg‘armaga ajrating.': 'Put 50% of income toward needs, 30% toward wants, and 20% into savings.', 'Xarid oldidan 24 soat kuting': 'Wait 24 hours before buying', 'Shoshilinch bo‘lmagan xaridni bir kunga kechiktiring. Ko‘pincha bu pulni tejashga yordam beradi.': 'Delay a nonessential purchase by a day. It often helps you save money.', 'Avval o‘zingizga to‘lang': 'Pay yourself first', 'Oylik tushishi bilan jamg‘arma uchun belgilangan summani alohida olib qo‘ying.': 'Set aside your planned savings as soon as your salary arrives.',
  },
  ru: {
    'O‘zbekcha': 'Узбекский', 'Tilni tanlang': 'Выбрать язык', 'O\'yin-kulgi': 'Развлечения',
    'PULINGIZNI BOSHQARISH VAQTI': 'ПОРА УПРАВЛЯТЬ ДЕНЬГАМИ', 'Rejalaringizga': 'Откройте путь', 'aniq yo‘l oching.': 'к своим целям.', 'Har bir xarajatni anglang. Har bir maqsadga yaqinlashing.': 'Понимайте каждый расход. Приближайтесь к каждой цели.', 'oddiy budjet qoidasi': 'простое правило бюджета', 'Hisobingiz himoyalangan sessiya orqali saqlanadi': 'Ваш аккаунт защищён безопасной сессией',
    'SHAXSIY HISOB': 'ЛИЧНЫЙ АККАУНТ', 'Hisob yarating': 'Создайте аккаунт', 'Hisobingizga kiring': 'Войдите в аккаунт', 'Moliyaviy ma’lumotlaringiz shu hisobda saqlanadi.': 'Ваши финансовые данные будут сохранены в этом аккаунте.', 'Davom etish uchun email va parolingizni kiriting.': 'Введите электронную почту и пароль, чтобы продолжить.', 'Kirish yoki ro‘yxatdan o‘tish': 'Вход или регистрация', 'Kirish': 'Войти', 'Ro‘yxatdan o‘tish': 'Регистрация', 'Ismingiz': 'Ваше имя', 'Ism va familiya': 'Имя и фамилия', 'Email manzil': 'Электронная почта', 'Parol': 'Пароль', 'Parolni yashirish': 'Скрыть пароль', 'Parolni ko‘rsatish': 'Показать пароль', 'Kamida 6 ta belgi': 'Не менее 6 символов', 'Parolingiz': 'Ваш пароль', 'Tekshirilmoqda…': 'Проверка…', 'Hisob yaratish': 'Создать аккаунт', 'Parolingiz serverda ochiq ko‘rinishda saqlanmaydi.': 'Пароль не хранится на сервере в открытом виде.',
    'Menyuni yopish': 'Закрыть меню', 'Menyuni ochish': 'Открыть меню', 'Hisobdan chiqish': 'Выйти из аккаунта', 'Menyu': 'МЕНЮ', 'Umumiy': 'Обзор', 'Xarajatlar': 'Расходы', 'Maqsadlar': 'Цели', '30 kunlik challenge': 'Челлендж на 30 дней', 'Har bir kichik qadam katta maqsadga olib boradi.': 'Каждый маленький шаг ведёт к большой цели.', 'Maqsadlaringiz': 'Ваши цели', 'Shaxsiy moliya': 'Личные финансы', 'Oldingi oy': 'Предыдущий месяц', 'Keyingi oy': 'Следующий месяц', 'Boshqaruv paneli': 'Панель администратора', 'Bildirishnomalar': 'Уведомления', 'Yangi yozuv': 'Новая запись', 'MOLIYAVIY HOLATINGIZ': 'ВАШЕ ФИНАНСОВОЕ ПОЛОЖЕНИЕ', 'Salom, ': 'Здравствуйте, ', 'Bugun pulingiz qayerga ketayotganini ko‘rib chiqing.': 'Посмотрите, куда уходят ваши деньги сегодня.', 'Shu oy': 'Этот месяц', 'Moliyaviy ko‘rsatkichlar': 'Финансовые показатели', 'Umumiy balans': 'Общий баланс', 'OYLIK': 'ЗА МЕСЯЦ', 'saqlanib qoldi': 'сохранено', 'Daromad va xarajat farqi': 'Разница доходов и расходов', 'Daromad': 'Доход', 'Jami daromad': 'Общий доход', 'Bu oy': 'В этом месяце', 'Xarajat': 'Расход', 'Jami xarajat': 'Общие расходы', 'daromaddan': 'от дохода',
    'PUL OQIMI': 'ДВИЖЕНИЕ ДЕНЕГ', 'Pulim qayerga ketmoqda?': 'Куда уходят мои деньги?', 'Hafta': 'Неделя', 'Oy': 'Месяц', 'Xarajatlar tarkibi': 'Структура расходов', 'Xarajat qo‘shsangiz, tarkibi shu yerda ko‘rinadi.': 'Добавьте расходы, чтобы увидеть их структуру.', 'Barcha kategoriyalar': 'Все категории', 'KATEGORIYALAR': 'КАТЕГОРИИ', 'Eng ko‘p xarajat ': 'Больше всего расходов: ', 'hozircha yo‘q': 'пока нет', 'kategoriyasida.': 'в категории.', 'Batafsil': 'Подробнее', 'Ko‘proq': 'Ещё', 'JAMI': 'ИТОГО', 'KATTA REJA': 'БОЛЬШИЕ ПЛАНЫ', 'Jamg‘arma maqsadi': 'Цель накоплений', 'MAQSAD': 'ЦЕЛЬ', 'Maqsad nomi': 'Название цели', ' yig‘ildi': ' накоплено', 'Maqsadga qolgan': 'Осталось накопить', 'Maqsadga yetish uchun': 'До цели', 'Maqsadga yetdingiz!': 'Цель достигнута!', 'taxminan ': 'примерно ', ' oy': ' мес.', 'oylik jamg‘armani kiriting': 'укажите сумму ежемесячных накоплений', 'Maqsad narxi': 'Сумма цели', 'Har oy yig‘aman': 'Откладываю каждый месяц', 'Jamg‘armaga pul qo‘shish': 'Добавить в накопления', 'Masalan, 100 000': 'Например, 100 000', 'Qo‘shish': 'Добавить', '30 KUNLIK CHALLENGE': 'ЧЕЛЛЕНДЖ НА 30 ДНЕЙ', 'Bugun tejadingizmi?': 'Удалось сэкономить сегодня?', 'Har kuni ozgina tejang. 30 kundan so‘ng o‘zgarishni his qilasiz.': 'Экономьте понемногу каждый день. Через 30 дней заметите результат.', ' kun': ' дн.', 'Bugungi qadam bajarildi': 'Шаг на сегодня выполнен', 'Bugungi qadamni belgilash': 'Отметить шаг за сегодня',
    'SO‘NGGI FAOLLIK': 'ПОСЛЕДНИЕ ОПЕРАЦИИ', 'Oxirgi tranzaksiyalar': 'Последние транзакции', 'Barchasini ko‘rish': 'Показать все', 'Bu oy uchun yozuvlar yo‘q. Birinchi tranzaksiyangizni qo‘shing.': 'В этом месяце записей нет. Добавьте первую транзакцию.', 'BUGUNGI MASLAHAT': 'СОВЕТ НА СЕГОДНЯ', 'Keyingi maslahat': 'Следующий совет', 'REJALASHTIRING': 'ПЛАНИРУЙТЕ', 'Kredit kalkulyatori': 'Кредитный калькулятор', 'Kredit summasi': 'Сумма кредита', 'Yillik foiz': 'Годовая ставка', 'Muddat': 'Срок', 'Oylik to‘lov': 'Ежемесячный платёж', 'ODDIY REJA, BARQAROR NATIJA': 'ПРОСТОЙ ПЛАН, УВЕРЕННЫЙ РЕЗУЛЬТАТ', 'Oylik pulni 3 qismga ajrating': 'Разделите месячный доход на 3 части', '50 / 30 / 20 qoidasi byudjetni tushunarli va boshqariladigan qiladi.': 'Правило 50 / 30 / 20 помогает легко планировать бюджет.', 'ASOSIY EHTIYOJ': 'НЕОБХОДИМОЕ', 'Avval zarur narsalar': 'Сначала необходимое', 'Uy, oziq-ovqat, transport va kundalik to‘lovlar.': 'Жильё, еда, транспорт и повседневные платежи.', 'SHAXSIY ISTAKLAR': 'ЖЕЛАНИЯ', 'O‘zingizga ham joy qoldiring': 'Оставьте место для себя', 'Hordiq, xaridlar va yoqtirgan mashg‘ulotlar.': 'Отдых, покупки и любимые занятия.', 'JAMG‘ARMA': 'НАКОПЛЕНИЯ', 'Kelajak uchun yig‘ing': 'Откладывайте на будущее', 'Kutilmagan holatlar va katta maqsadlar uchun.': 'На непредвиденные расходы и большие цели.', 'Yuqoriga': 'Наверх', 'Ma’lumotlaringiz faqat ushbu qurilmada saqlanadi': 'Данные хранятся только на этом устройстве', 'YANGI YOZUV': 'НОВАЯ ЗАПИСЬ', 'Tranzaksiya qo‘shish': 'Добавить транзакцию', 'Nomi': 'Название', 'Masalan, tushlik': 'Например, обед', 'Summa': 'Сумма', 'Kategoriya': 'Категория', 'Sana': 'Дата', 'Tranzaksiyani saqlash': 'Сохранить транзакцию', 'Yopish': 'Закрыть', 'Oziq-ovqat': 'Продукты', 'Transport': 'Транспорт', 'O‘yin-kulgi': 'Развлечения', 'Xaridlar': 'Покупки', 'Uy va aloqa': 'Дом и связь', 'Boshqa': 'Другое', 'Ish haqi': 'Зарплата', 'Qo‘shimcha daromad': 'Дополнительный доход', 'so‘m': 'сум', 'oy': 'мес.',
    'Moliya sahifasi': 'Финансовая панель', 'Chiqish': 'Выйти', 'BOSHQARUV': 'УПРАВЛЕНИЕ', 'Foydalanuvchilar': 'Пользователи', 'Hisob holatini boshqaring va kerak bo‘lsa sessiyani bekor qiling.': 'Управляйте аккаунтами и при необходимости завершайте сеансы.', 'Yangilash': 'Обновить', 'jami hisob': 'всего аккаунтов', 'Faol: ': 'Активны: ', 'To‘xtatilgan: ': 'Приостановлены: ', 'RO‘YXAT': 'СПИСОК', 'Hisoblar': 'Аккаунты', ' ta': '', 'Ro‘yxat yuklanmoqda…': 'Загрузка списка…', 'Foydalanuvchi': 'Пользователь', 'Ro‘yxatdan o‘tgan': 'Зарегистрирован', 'Holat': 'Статус', 'Amal': 'Действие', 'To‘xtatilgan': 'Приостановлен', 'Faol': 'Активен', 'Ruxsat berish': 'Восстановить доступ', 'Chiqarish': 'Приостановить', 'Hozircha ro‘yxatdan o‘tgan foydalanuvchi yo‘q.': 'Пока нет зарегистрированных пользователей.', 'Hisobni to‘xtatish foydalanuvchini darhol chiqaradi; moliyaviy ma’lumotlari o‘chirilmaydi.': 'Приостановка аккаунта завершает сеанс; финансовые данные не удаляются.', 'Sessiya yakunlandi. Qayta kiring.': 'Сеанс завершён. Войдите снова.', 'Hisobingiz sessiyasi bekor qilindi.': 'Сеанс вашего аккаунта был отозван.', 'MoneyMaster yuklanmoqda': 'Загрузка MoneyMaster', 'Hisob ma’lumotlari yuklanmoqda': 'Загрузка данных аккаунта', 'Juda ko‘p urinish. 1 daqiqadan keyin qayta urinib ko‘ring.': 'Слишком много попыток. Повторите через минуту.', 'Hisobga qayta kiring.': 'Войдите в аккаунт снова.', 'Hisob faol emas yoki sessiya bekor qilingan.': 'Аккаунт неактивен или сеанс был отозван.', 'Administrator huquqi kerak.': 'Требуются права администратора.', 'Ism va to‘g‘ri email kiriting.': 'Введите имя и корректный адрес электронной почты.', 'Parol kamida 6 ta belgidan iborat bo‘lsin.': 'Пароль должен содержать не менее 6 символов.', 'Bu email bilan hisob mavjud.': 'Аккаунт с таким адресом уже существует.', 'Email yoki parol noto‘g‘ri.': 'Неверный адрес электронной почты или пароль.', 'Foydalanuvchi topilmadi.': 'Пользователь не найден.', 'Holatni yuboring.': 'Укажите статус аккаунта.', 'So‘rov bajarilmadi.': 'Не удалось выполнить запрос.', 'Server API JSON javob bermadi. Vercel deploy sozlamalarini tekshiring.': 'Сервер не вернул API JSON. Проверьте настройки развёртывания Vercel.', 'hisobini vaqtincha to‘xtatib, faol sessiyalarini bekor qilamizmi?': 'Приостановить аккаунт и завершить активные сеансы?',
    '50 / 30 / 20 qoidasini sinab ko‘ring': 'Попробуйте правило 50 / 30 / 20', 'Daromadning 50 foizini ehtiyojlarga, 30 foizini istaklarga va 20 foizini jamg‘armaga ajrating.': 'Направляйте 50% дохода на необходимое, 30% на желания и 20% в накопления.', 'Xarid oldidan 24 soat kuting': 'Подождите 24 часа перед покупкой', 'Shoshilinch bo‘lmagan xaridni bir kunga kechiktiring. Ko‘pincha bu pulni tejashga yordam beradi.': 'Отложите необязательную покупку на день. Это часто помогает сэкономить.', 'Avval o‘zingizga to‘lang': 'Сначала заплатите себе', 'Oylik tushishi bilan jamg‘arma uchun belgilangan summani alohida olib qo‘ying.': 'Откладывайте запланированную сумму сразу после получения зарплаты.',
  },
}

const LanguageContext = createContext(null)
const localeByLanguage = { uz: 'uz-UZ', en: 'en-US', ru: 'ru-RU' }

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = localStorage.getItem('moneymaster-language')
      return saved in localeByLanguage ? saved : 'uz'
    } catch {
      return 'uz'
    }
  })

  useEffect(() => {
    document.documentElement.lang = language === 'uz' ? 'uz' : language
    document.title = language === 'en' ? 'MoneyMaster UZ — Personal finance' : language === 'ru' ? 'MoneyMaster UZ — Личные финансы' : 'MoneyMaster UZ — Shaxsiy moliya'
    try { localStorage.setItem('moneymaster-language', language) } catch { /* Storage may be unavailable. */ }
  }, [language])

  const translate = (text) => {
    const dictionary = translations[language]
    if (dictionary?.[text] !== undefined) return dictionary[text]
    const trimmed = text.trim()
    const translated = dictionary?.[trimmed]
    if (translated === undefined || !trimmed) return text
    const start = text.indexOf(trimmed)
    return `${text.slice(0, start)}${translated}${text.slice(start + trimmed.length)}`
  }
  const value = { language, locale: localeByLanguage[language], setLanguage, translate }
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}

export function LanguageSelect() {
  const { language, setLanguage, translate } = useLanguage()
  return (
    <label className="language-select">
      <span className="sr-only">{translate('Tilni tanlang')}</span>
      <select aria-label={translate('Tilni tanlang')} value={language} onChange={(event) => setLanguage(event.target.value)}>
        <option value="uz">UZ</option>
        <option value="en">EN</option>
        <option value="ru">RU</option>
      </select>
    </label>
  )
}

function translateTree(children, translate) {
  return Children.map(children, (child) => {
    if (typeof child === 'string') return translate(child)
    if (!isValidElement(child)) return child
    const props = {}
    for (const [name, value] of Object.entries(child.props)) {
      if (name === 'children') continue
      if (typeof value === 'string' && ['aria-label', 'aria-description', 'placeholder', 'title', 'alt'].includes(name)) props[name] = translate(value)
    }
    return cloneElement(child, { ...props, children: translateTree(child.props.children, translate) })
  })
}

export function Localized({ children }) {
  const { translate } = useLanguage()
  return translateTree(children, translate)
}